# Generated by Django 2.0.4 on 2018-04-30 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
